version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
    depends_on:
      - backend
    command: ["node", "app.js"]

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src
    # depends_on:
    #   - redis
    #   - postgres
    # command: ["python", "kronaclub/manage.py", "runserver", "0.0.0.0:8000"]
    command: ["sh", "-c", "cd kronaclub && gunicorn --workers=3 --bind 0.0.0.0:8000 kronaclub.wsgi:application"]


  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paSsWoRd1

volumes:
  frontend_data:
  backend_data:
  postgres_data:
